/*
 * Teka Kata Neon — kamus tekaan bagi perkataan 4 huruf.
 *
 * Dimuatkan bila perlu: hanya panjang yang sedang dimainkan diambil.
 * Jauh lebih luas daripada kumpulan jawapan, kerana menolak perkataan yang
 * pemain tahu betul adalah perkara paling menjengkelkan dalam permainan ini.
 * Daripada hermitdave/FrequencyWords (lesen MIT, korpus OpenSubtitles).
 */
(window.CIPHER_MS_DICT = window.CIPHER_MS_DICT || {})[4] = `
  aaaa aaah aadi aagh aahh aaja aaku aane aang aapa aasa aata aaya aaye abad abah abba
  abdi abee abeg abel abhi abik abin abis able acah acak acap acar aceh aces acha ache
  acme acre acuh adab adam adat adek adem ader adhd adik adil adit adlh adoe adoi aduh
  adui aduk aeon aero afro agak agam agar agen agni agra agus agwi ahab ahad ahem ahhh
  ahii ahli ahoy aids aihh aing aint aish aitu aiya aiyo aizu ajak ajal ajam ajar ajax
  ajen ajer ajit ajob ajuk akad akah akak akal akan akar akau akil akio akku akmu aksi
  akta akua akui akul akun akur akut akuu alaa alaf alah alam alan alas alat alby aldo
  alec alek alen alfa alga algi algo alif alih alik alim alka allo aloi alok aloo aloy
  alps also alto alur alva amal aman amar amat ambo amen ames amik amin amir amis amit
  amma ammi ammo amol amor amos amps amuk amun anah anak anal anbu ancl anda ando aneh
  anih anil anju anka ante anti anuj anus aogu aoki apaa apai apap apat apel aper apex
  apiq apna apne apni apoc apos appa apte aput aqua arab arah arai arak aral aras arbi
  arby arca arch area aren arer ares argg argh argo aria arif aris arka arks arlo arma
  arms army aron arre arry arti arts artu arun arus arya asah asai asak asal asam asap
  asas asem aset ashe asid asik asin asli asma asuh atap atas atau atcu atok atom atta
  atuk atul atur aula auns aunt auto aviv avon avre awac awah awai awaj awak awal awam
  awan awas awat away awek awet awka awol axel axis ayah ayak ayam ayan ayat ayng ayoh
  ayuh ayun azab azad azam azan aziz azog baba babe babi babu baby baca bach back bada
  badi baek baez bagi baht bahu baik bail bain bait baja baji baju baka baki baku bala
  bale bali ball balu bama bana band bane bang bank banu bapa bara bard bare barf bark
  barn barr bart baru bary basa base bash basi baso bass bata bath bats batu baug baum
  baut bawa baya bayi bayu baze bcci beam bean bear beat beau bebo beca beck beda bedi
  beef beek been beep beer begi bego behl beii bein bejo beks beku bela beli belt belu
  bend benz beom bepo berg beri berk bern beru besi best beta beto betu bevy beza bffs
  bgmn bhai bhak bhun biak bial biar bias bida bien biff biia biji biju bike bila bile
  bilk bima bina bing bini bira biri biro biru bisa bisu bite bius blah blak blam bleh
  bleu blip blob bloc blog blok blow blue blur blus boar boat boba bobo boca bodo body
  boeh boet bogo bogs bois boku bola bold bole bolg bolo bolt boma bomb bond bone bong
  bono boob book boom boon boop boot boov booz bora borg born bose boss both bott bout
  bowl boya boyd boys boyz boze bozo brad brah bran brat brea brek brer bret brie brij
  bros bsaa btul buad buah bual buan buas buat bubs buck bucu buda budi buen buff bugs
  buih buka buke buku bule buli bull bulu bumi bump bums bund bung burg burj burn burr
  burt buru bury busa bush bust busy buta butt buzz byte cabe cabo caci cade caen cafe
  cage caii cail cain cair cait cake cale cali call calm came camp cams cane cang cape
  capo capp caps card care carl carr cars casa case cash cast cath cato cats cave caws
  ccpd ccpn cctv ceko cela cell celt cent cepu ceri cern ceti cewe cgnn cgpa chae chai
  chak chal cham chan chao chap char chat chau chaz chee chef chek chen chet chew chez
  chic chif chik chin chip chit chiu choe choi chon choo chop chor chot chou chow choy
  chud chug chui chuk chul chum chun chut chuy ciao cien cili cina cine cing ciri cita
  cite city cium ckit clan clay club cnri coal coat coba cobb coca cock coco code coif
  coin coke cola cold cole coli colm colt coma come comm como comp cong conn cons cook
  cool coon coop cops copy core cork corn corp coug coup cous cove cque crab crap cray
  crew croc crot crow cruz cryo cuai cuak cuam cuba cube cubs cuci cucu cuff cuih cuit
  cujo cuka culp cuma cume cumi cung cure curi curl cuta cute cuti cuts daah dada dade
  dadu dady dagu dahi dahl dail dain dais daji daju daki daku dala dalm dama dame damn
  damo dane dang dank dano danz dapt dard dare darf dark darn daro dart dash dass data
  date dati dato daud daun daur daus dave davy dawg daya days daze dazs ddan deac dead
  deaf deal dean dear debu deck dedh deep deer dees deja deje deke deli demi demo deng
  dent deok deon depa depp dera desa desh desi desk dess devo dewa dewi dhai dial diam
  diao dias diaz dibs dice dick didn died diem diep diet diff dikh dima dime ding dini
  dino dior dios dire diri dirk dirt disc dish disk diss dius diva dive diya dobi dock
  dodo does dogg dogs doha dohr doin dojo dome domo done dong donk dono dont doom doon
  door dope dork dorm dosa doss dost doug dowd dowh down dpat drac draf drag dram draw
  drax drew dron drop drpd drug drum duan duck duda dude duel duen duet duga duit duiu
  duka duke duli duls dulu dumb dump dung dunk dunn dupa duri dust duta duti dutt duty
  dyer dyke each eadu earl earn east easy eats ebay eben echo ecto edan edar edge edit
  eeee eema eeny efek effy egen eggs eggy egil eheh ehem ehhh eide eiji eiok eise ejat
  ejaz ejek ejen ekar eked ekik ekor elak eleh elia elit elmi elmo elms elok emak emas
  emel emil emir emmm emph enak enam endo ends enzo epal epic epik epps erat eren eret
  eric erie erik erit erkk ermm eros errr erso erti ertz esai esei esok espn esuk etch
  eter etik etis etos ette eugh euro evac evan evel even ever evii evil ewen exit expe
  expo eyed eyes eywa ezra face fact fade faia faii fail fair fait faiz fake faks fall
  fame fana fang fans farm fart fasa fase fast fata fate fats faul faut faxx faza fear
  feat feck feds feeb feed feel feet fell felo felt fema feng fenn feri fest fett feud
  feza fico fido fifa fiji fikr file fili fill film find fine finn fire firm fisa fish
  fisk fist fiti fitz fius five fkir flag flap flat flay flea flew flex flip floo flop
  flos flow flux fogg foie fold folk fong font food fooi fool foon foot ford fork form
  fort fosa foto foul four frag free fret frey frio from fros frou frum frye fuck fudd
  fuhu fuji full fund fung funk fury fuse fusi fuss fuzz gabe gaff gaga gage gaia gaib
  gaji gala gali gals galt galz game gana gang gann ganu gapo garf gari garm garn garu
  gary gasp gate gato gaul gaun gave gawd gaya gaza gccf gchq gcpd gear geat gebu gede
  gedo geek geer geet geez geli gema geng genk geon gesa gets getz geun ghai ghar ghat
  ghul giat gift giga giia gila gile gimp gini gino giri girl gita gitu give giza glam
  glee glif glob glow goal gobi goda gods goes gogh gogo goid goin goji goki goku gold
  golf goli gone gong goni good goon goop gooz gopi gora gore gorg goro gort gosh goss
  gota goth goto gots gout govt goya grab grad graf grak gram gran gras gred greg grey
  grib grid gril grim grin grip gris grmk grow grrr grub grug grun grup gsdf guac guam
  guan guci guha gula gulf guli gump gums guna gung guni guns guri guru gusi guys gwan
  gwei gwon gyan gyro gyun haaa haag haah haan haas haba hack hadi hado hagu haha hahn
  haho haid haif haig haii hail hain hair hait haji haku hala hale half hall halo halt
  hama hame hamm hand hang hank hans hany hara hard hare hari harm harp hart haru harv
  hash hasn hate hati haul haus haut have hawa hawk haze head heal hear heat heck heee
  heen hehe heii heil heip held heli hell helm helo help helu hema hemi henk hepe hera
  herb herc here herm hero herr hess hias hiba hida hide hidu high hiii hijo hike hill
  hilo hina hind hino hips hire hiro hish hiss hist hits hive hiya hkia hmmm hmph hobb
  hobi hock hoda hogg hoho hoid hoji hoki hola hold hole holi holo holt holy homa home
  homo hona hong honk hood hook hoon hooo hoop hore horn hors hoss host hour hout howl
  hoyd hoyt huai huat huck huey huge hugh hugo hugs huhh huhu hula hulk hull hulu hume
  humm hump hums hung hunh hunk huns hunt hura hurt huru hush husy hutt huuh huys huzi
  hyah hyde hyuk hyun iaea iagi iail iain iaiu iaka iaku iama iari iast iate iaut ibis
  icac icbm icon icpo idak idea ideo idfl idid idli idol idul idun idws ieds ieft ieid
  ifab ifbb ifwe iggs iggy igor igot ihat ihop ihro iies iife iiit iike iist iitu ijin
  ikal ikan ikat ikea ikol ikon ikut ilah ilmu imam iman imei imej imir imli imry imun
  imut inai inap inca inch inci indo indu indy info ingi inii inil inks inti into ioin
  iong iook iori iose iost iove iowa ipad ipar ipod ipta irak iran iraq iras iron isai
  isap isco isda ishq ishu isil isla isle issa itch item itik itna itni itul itus iuar
  iuck iupa ivan ivar ives izin izzy jaan jace jack jaco jadi jaga jago jaha jahe jaii
  jail jain jaka jake jaki jala jamu jang jani janu japs jari jasa jati jatt jauh java
  javi jawa jawn jaws jaya jaye jayu jazz jebe jeda jedi jeep jeez jefe jeff jeju jela
  jeli jemu jeng jeol jeon jerk jeti jets jian jiao jika jiko jima jimi jing jinx jiro
  jism jitu jiwa jiwe jiya jobs jock joel joes john join joke joki jong jono jony joon
  jose josh joss jovi jsoc juai jual juan judd jude judo juga juhu july jump jung juni
  junk junu juri juru just juta jute kaal kaca kada kadi kado kaew kafe kage kahl kahn
  kaii kail kain kais kait kaji kaka kake kaki kaku kale kali kalo kalu kama kame kami
  kamp kamu kana kane kang kanu kaok kaos kapa karl karq kart karu kasa kash kasi kata
  kato katz kaul kaum kaun kaur kaus kaut kauu kave kaya kayo kayu kaze kean keaw kebo
  keci keep keja keje keji keju keli kell kels kelu kema kemo kemp kemu kena kene keng
  kent kepa kepo kept kera kerr keta keys khac khal kham khan khao khar khas khat khon
  khor khud kian kiat kiba kick kido kids kiet kiev kiii kiki kiko kili kill kilo kimi
  kimo kind king kini kinu kios kirk kisi kiss kita kite kito kiub kiwi kiya kkom klab
  klac klan klau klik klip klon kloy klub kluc klum klux kmau knee knew knot know knox
  koba kobe koch kode kodi kofi koga kohl koin koir koji koki koko kola koma kome komi
  kong koni kono kony kook koor kopi kopn kord korg korn kosa kota kote koto kprs krab
  kraf krav kray kree krei krem kren krew krim krom kroo kror krub krug krum krup krut
  ktia kuad kuah kuai kuak kuan kuar kuat kuba kubu kuch kuda kudi kudo kueh kuen kuih
  kuil kuis kuiz kujo kuka kuke kuku kuli kumu kung kuno kupu kura kurt kush kutu kuze
  kwai kwan kwek kwik kwla kwok kwon kyln kyra kyun laaa laba labs labu lace laci lack
  lada lads ladu lady laga lage lagi lagu laid lain lair laju lake lakh laki laku lala
  lali lalo lalu lama lamb lamu land lang lans laos lapd larb lars lash last lata late
  lauk laun laut lava lawa lawn lays layu lazy lcac ldea lead leaf leak lean lebi leco
  leen left lega lego legs leih leka lemi lena lend leng leno lens lent leon lery less
  lesu lets levi levy lewa liak liam liao liar liat lick lidi lied lien lies life lift
  liga like liku lili lilo lima lime limo linc line ling lini link lino lion list lite
  lito liur liut live liya liye lkut llmu llsa lndy load loan lobi lobo loch lock loco
  lodi loeb loew loga logi logo lohi loji loki lone long look loon loop loos lope lord
  lose lost lota lots loud loup love lowe loya lpad lraq lsat luah luak luar luas luca
  luck lucu luda lude lugo lugu luis luiz lujo luka luke luna lund lung lupa lupo lutz
  lvan lwas lxas lyla lyle lyon lyra maaa maaf maam maan maar mace mach mack macm macy
  made madu maek maen maga mags maha mahu maid mail main mais maju maka make maki mako
  maks male mali mall malt malu mama mami mana mane mani mann mano manu many mapo maps
  marc mare mari mark marl mars mart marv marx masa mash masi mask maso mass mata mate
  math mati matt matu maui maul maut maya mayo mays maze mazo mbak mcam meal mean meat
  mech meds meen meer meet mega mein meja meka meld meme memo meng menu meow mera merc
  mere meri merk mesa mess mete meth metz mffa mham mhhh mhok miao mica mick micr midi
  mien migi miho mika mike miki miko mila mile milf mili milk mill milo mime mims mind
  mine ming mini mint miny misa misi miss mist mita mitu miya mmhh mmmm moat moby mode
  modi moga mogi mogs moha mohd mojo moka mole moma momo mong monk mono mont mood mook
  moom moon more mori morn moro mort mose mosi moss most mota moto mott move mpsj mqrn
  msih mslh muah muak mual muat muay mubi much muda mudd mudi muia muir muka muke mula
  mulu mung munh musa muse must muto mutu muza mwah myca naam naan nabi nada nadi nado
  nadu naga nago nahi naib naif naik nair naka naku nale nama name nami namo nand nang
  nano napa nape napi narc nasa nash nasi nate nath nato navy naya naza nazi ncaa ncic
  ncis ncpd neal near neck need negi neha neij neil neka nemo neon nerd nerf neri nero
  ness nest news newt next nffa ngan ngek ngga ngok ngou nhan niat nibs nice nick nico
  niff nika niko nila nili nils nilu nima nine ning nion nira niro nite nivi niya noaa
  noah noam nobu nock noda noed noir nome none nong noor nope nori norm nose nota note
  nova novi nozz ntah ntar ntoc ntsb ntuk nuck nuff nuke null nuna nung nunn nunu nuri
  nurv nuts nuun nuwa nuys nyah nyam nyer nyet nypd nyum oahu oaks oang obat obie obol
  obor obul octa oden oder odin odmg ofis ogah ogos ogre ohao ohem ohhh ohio ohok ohya
  oieh oiii oink ojai okay okeh okei okey okie okra okun olaf olah olde oleg oleh omar
  omel omni onar once ones oniy only onyx oooh oooo oops ooty opar open oper oppa opps
  opsi oral oram orca orcs orde ordo ordy oren oreo orga orzz oslo otak otis otot otsu
  otto ouch ours oval oven over ovie owal owen owls ozai ozil ozma ozon ozzy paan paar
  paas pace pack paco pacu pada padi pads padu pagg pagi paha paid paim pain paip pair
  pake paku pala palm palu pang papa papd papi papp para pari park part paru pasa paso
  pass past pasu pata path pati pats patu paul paun paus paut pawn paya payu peak pear
  peas peck pede peed peek peep peer peez pega pegi peha pein peka peko pele pelu pena
  peng penn pepe perg perp pers peru perv peso pete peti pfft phak phen phew phir phon
  phra piaf pian piau pibb pibg pick pico picu pied pigs piir pike pile pili pill pilu
  pina pind pine ping pink pinn pint pion pipa pipi pips pita pits pitt pius piya piza
  pker plag plak plan plat play plet plis plot ploy plug plum plus pods poem pogo poie
  poin poke pola poli polo pond pong poni pont pony poof pook pool poom poop poor pope
  popi popo pops pora pori pork porn port pose posh post poto pott pour pows poyo ppac
  prai pray pred pref prem prep prez pria prim prit prix prob prof prom prop prun psst
  psti ptsd puak puan puas puck pued puff puja puji puku pula pull puma pump puna pune
  pung punk puny pura pure puri push puss puta puti puto putt pyar pyro qazi qian qiao
  qing qkay quad quan quid quil quis quit quiz quot raah raat raba rabu race rach rack
  radi rads rafe rafi raft raga rage ragu raha rahu raih rail rain raja raje raji rajo
  raju raka rakh rali rama rami ramu rand rane rang rank rape raph rapi raps rare rasa
  rase rasi rata rate ratu rauf raul raut ravi rawa raya rays rayu raza raze read reai
  real rear reda reds reed reel reep regu reid reka rela rell remi remz rend reno rent
  renu rest reti reum reve revs rexy reza rezo rhib riak rial rias riba ribu rice rich
  rick rico ride riff rigs riil riis rika riko rima rind ring rink riot risc rise risk
  ritz riuh riya rizu road roan roar roat rock rojo rold role roll rolt roma rome romi
  romo rone rong roof rooh rook room roop root rope ross rotc roth roti roux rozz rpgs
  ruah ruam ruas rudi rudy ruff rugi ruiz ruji ruka rukh rule rumi runt rupa rupe rusa
  rush russ rute ruyi ryan ryuk saab saag saal saat saay sach sack sadd sadi safe saga
  sage sahi said sail sain sait saiz saja saje saji saka sake saki saks saku sale salk
  salt sama same sami samy sana sand sang sano sans sant sanu sapa sape sapi sapo sapu
  sars sasa sata sate sati sato sats satu saua sauh saul saus save sawa sawi sawo saya
  saye says sayu scam scan scat scav scpd scud scum seai seal seat seba sede sedi seek
  seem seen sees seet sefa segi seii seks sell selo semi semu send seng seni sent seob
  seok seol seon sepi sept seri seru sesi sesl seth seti setu sewa sexy sfpd shah sham
  shan shao shaq shat shaw shed shek shem shen shep shes shhh shif shih shil shim shin
  ship shit shiu shiv shoe shoo shop shot show shri shui shum shun shut siai sial siam
  siap siar siat siau sica sick sida side sidi sieg sifu sign siia sikh siku sila silk
  silo simi sims simu sing sinh sini sink sinn siot siow sipa sipe sipi sire siri sisa
  sisi siss sita site sith situ siul siur siut siva siya size skaf skak skal sket skil
  skim skin skip skit skop skor skrg skru skye slam slap slim slip slit slop slot slow
  slug smee smek smit smua snap snek snip snow snsd soai soal soba sobs soda sofa soft
  sohn soho soil soju soke sola sole solo soma some sona song soni sono sons sonu sook
  soon soot soph sora sore sori sorr sort sory sosa sota soto soul soup sour sous soya
  soze spam span spar spec spek spin spit spot spud ssbi sshh sssh ssst sstt staf stan
  stay stef stel stem sten step stew stig stik stim stnk stok stop stor stud styx suai
  suam suap suar suay subs such suci suck suda sudi sudu suet sufi sugi suhu suis suit
  suiz suka suko suku sull sulu suma sumi sumo sung suns sure suri suru susu sven swag
  swan swap swat sway syaa syak syal syam syif sync syok syor syut taam taat tabi taco
  tada tadi tael tags taha tahu taik tail taip tais taja taka take taku tale tali talk
  tall tama tame tamp tamu tang tank tape tapi tapp tari tarn taro tarp tars tart tase
  tasi task tata tato tatp tats tatu taun taur tawa taxi taya tcri tdak team tear tebu
  tech tega tego teii teka teki teko teks tela tell tema temu teng tent tepi tepu tere
  teru test teta tevi text thai than that them then they thin this thor thud thug tiak
  tian tiap tiba tibi tich tick tida tide tido tiel tien tier ties tifa tiga tika tiki
  tile till time ting tinh tink tiny tipe tips tipu tiri tiru tisu tito tits titu titz
  tiub tiun tiup tivo tkau tnya tock todd toei toes tofu toga toge toki toko told toll
  tomb tona tone tong tons took tool toom toot topi topo tora tork torn toro toru tosa
  tote toto tour town toys trak tram tran trap trav tree trek trem tren tres trev trey
  trik trim trin trio trip tris tron troy truc true truk trus tsai tsan tsar tsat tsim
  tsin tsui ttss tuah tuai tuam tuan tuas tuba tube tubi tuck tuco tudu tugu tuha tuil
  tuju tuli tull tuna tune tung turk turn tusk tutu twin type uang ubah uban ubat ubbe
  uber ubur ucap ucla udah uday udik udon udre ueno ufuk ugga ughh ugly ugut uhmm uhuk
  ujud ukir ukur ulah ular ulas ulat ulit umah umar umat umbi ummm umph umum umur undi
  ungu unik unit univ unix unni unsc unta untu unuk unum uozu upah upon upto urag ural
  urat urca urdu urgh urin uris uruk urus urut usah usai usap used user usha usia usik
  usil usir usse usul usus utah utan utku utte utuh utuk utus uzur vaca vada vail vain
  vali vamp vane vase vass vatt veer vega vegh velu vena vent vern very vesp vest veto
  vexy vibe vica vice vich vick vics vier viet view vika vila vile vine vino virg viru
  visa visi vito vlad void volo volt vora voss vous vvip waco wada wade waen wahh waid
  wain wait waja wake wali walk wall walt wang want ward warg warm warn warp wars wash
  wasn waso wasp wate watt wave ways wckd wear webb weed week weii weil wein well weng
  went were west weyh wham what whee when whew whip whis whit whiz whoa whom whoo whos
  whow wich wick wide widf wies wife wifi wiii wiki wild will wind wine wing wink winn
  wins wipe wira wire wise wish with woah wohi woii woke wolf wong woni wont wood woof
  wook wool woon wooo woow wopr word work worm woww wrap writ wuba wuss wuyi xbox xian
  xiao xiau xing xiqi xixi xoxo xray xuan yaaa yaad yaah yaar yada yagn yahi yaho yala
  yale yama yamg yana yang yank yard yash yasu yaya ybor yeah year yeke yela yell yelp
  yelu yeon yeow yeti yien yiff ying yips ykau ylva ynag yoda yoga yogi yolo yong yoon
  york yosh youd youl your yoyo yuan yuck yuda yuen yuji yuka yuki yuko yule yume yumi
  yung yura yuri yuza zaas zach zack zaef zaid zaim zaja zamp zane zang zaya zeke zemo
  zeng zeni zero zeta zeus zeze zhao zhen zhou zhuo zien zima zimo zina zing zink zion
  zira zito zoey zoil zona zone zook zoom zord zorn zoro zoya zuba zuko zulu zurg zuse
  zwei
`.trim().split(/\s+/);
